### ISSUE TITLE
Implement set union more optimally.

### ISSUE THREAD

**Issue by farziengineer** [farziengineer/underscore_cpp#24]
@blowdee Please look into it.

**Comment by farziengineer** [comment]
Use this for pointers https://stackoverflow.com/questions/12863904/algorithm-to-find-intersection-of-two-sets-without-using-any-data-structure

**Comment by WizardOfArc** [comment]
I'd like to take a stab at it - this is Union yes?

**Comment by farziengineer** [comment]
@WizardOfArc you can proceed with it.

**Comment by WizardOfArc** [comment]
https://github.com/farziengineer/underscore_cpp/pull/25 (feedback is welcome)

**Comment by farziengineer** [comment]
Thanks @WizardOfArc . #25
