### ISSUE TITLE
Sorting a const container

### ISSUE THREAD

**Issue by Gotham13121997** [farziengineer/underscore_cpp#28]
https://github.com/farziengineer/underscore_cpp/blob/ced412c47cc05ebaeb9b57437e625e16b28600bc/underscore.cpp#L253

It is not possible to sort a const container so this line is giving an error. We can either pass non const container or a set. Please look into it @farziengineer

**Comment by farziengineer** [comment]
I think we should pass the containers by value just like we have in intersection, so that the original containers also do not change (while sorting) and we do not need to const.
