### ISSUE TITLE
Add indentation 

### ISSUE THREAD

**Issue by farziengineer** [farziengineer/underscore_cpp#35]
Add appropriate indentation in `underscore.cpp` file. All the implementation is left-aligned.

**Comment by hjain5164** [comment]
I can see that indentation has been there.

**Comment by farziengineer** [comment]
I dont think so. Maybe you are looking the code from GitHub, and the code they show is slightly seen indented. Can you clone it and check it out.

**Comment by hjain5164** [comment]
Ok I will do that
