### ISSUE TITLE
While loop bracket not closed.

### ISSUE THREAD

**Issue by Gotham13121997** [farziengineer/underscore_cpp#45]
https://github.com/farziengineer/underscore_cpp/blob/1cbccc7abe4bed208e971b330fc2d06f787d8651/underscore.cpp#L281

**Comment by farziengineer** [comment]
Before taking up this issue please ask this to be assigned. We do not want more than one person to work on the same issue.

**Comment by shubhamcr** [comment]
I think the curly brace for the while loop at line 288 is also not closed. Can I take this one ?

**Comment by Gotham13121997** [comment]
sure

**Comment by shubhamcr** [comment]
Please assign it to me

**Comment by farziengineer** [comment]
Sure @shubhamcr go ahead.

**Comment by shubhamcr** [comment]
I have raised the pull request. Kindly review: https://github.com/farziengineer/underscore_cpp/pull/46

**Comment by shubhamcr** [comment]
I want to add one more comment that please use some styling/indentation check tool for your repository. The indentation gets messed up when the changes are made in the local repo and pushed to origin.

**Comment by Gotham13121997** [comment]
@shubhamcr  thats a nice suggestion we will look into it. Thanks.

**Comment by Gotham13121997** [comment]
closed via #46
