### ISSUE TITLE
Change namespace "underscore" to "_" 

### ISSUE THREAD

**Issue by farziengineer** [farziengineer/underscore_cpp#48]
https://github.com/farziengineer/underscore_cpp/blob/488f74eed359f06f49d27cfad4ba835bb4c0062a/underscore.cpp#L4

**Comment by yashbhutoria** [comment]
done at #50

**Comment by farziengineer** [comment]
@yashbhutoria please read the contribution guidelines before contributing. Anyway I am merging your PR.
Please ask to assign the issue to yourself before starting any work. 
Thanks :)
