### ISSUE TITLE
Link in README for underscore.js should open in new tab

### ISSUE THREAD

**Issue by farziengineer** [farziengineer/underscore_cpp#56]

**Comment by melaniew** [comment]
Hi, may I fix this?

**Comment by farziengineer** [comment]
Sure

**Comment by melaniew** [comment]
Hi, I didn't realize this is actually a persistent issue with Markdown. It appears Github strips out the target="_blank" (in any form) upon rendering for some reason.  This [link] (https://stackoverflow.com/questions/40026947/open-new-tab-on-link-markdown) gives a nice background explaining the cause.

**Comment by farziengineer** [comment]
https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link

**Comment by farziengineer** [comment]
@melaniew thanks, I think you are right.
