### ISSUE TITLE
License: MIT?

### ISSUE THREAD

**Issue by gubatron** [farziengineer/underscore_cpp#70]
I'll go ahead and postulate MIT License as the way to license this project.
This way it can be used in both commercial and non-commercial projects, true freedom.

**Comment by farziengineer** [comment]
MIT might be considered better choice than GPL in our case. As far as I understand it, a GPL licensed code cannot be combined with something proprietary. Am I correct ?

**Comment by gubatron** [comment]
Yes, GPL is a pain because it can only be used with GPL or Apache, forced "freedom" isn't freedom in my book and it only hinders adoption. MIT on the other hand, you do whatever you want.

**Comment by gubatron** [comment]
[PR Submitted](https://github.com/farziengineer/underscore_cpp/pull/71)
