### ISSUE TITLE
Short form for functions

### ISSUE THREAD

**Issue by farziengineer** [farziengineer/underscore_cpp#77]
https://github.com/farziengineer/underscore_cpp/commit/e06e71ce316b51fbe3ba8bf3d996e17b941db232#diff-9a483ac18b44989323c99267b1de1553R19

It sounds like a good idea to do it for every function we have.

**Comment by gubatron** [comment]
I believe the only one left would be `transform`, I'm not sure what this function is supposed to do so I didn't  create a short form version of it, could not find a function named "transform" in underscore js.
